project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: HYDRV/app/src/main/res/values/strings.xml
    translation: HYDRV/app/src/main/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        ar: ar
        cs: cs
        cs-CZ: cs
        fil: fil
        pt-BR: pt-rBR
        zh-CN: zh-rCN
    update_option: update_as_unapproved
